//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_cbteVta
    {
        public fa_cbteVta()
        {
            this.fa_cbteVta_det = new HashSet<fa_cbteVta_det>();
        }
    
        public int IdEmpresa { get; set; }
        public string IdCbteVtaTipo { get; set; }
        public decimal IdCbteVta { get; set; }
        public string num_CbteVta { get; set; }
        public int IdSucursal { get; set; }
        public int IdPuntoVta { get; set; }
        public decimal IdCliente { get; set; }
        public bool estado { get; set; }
        public string observacion { get; set; }
    
        public virtual ICollection<fa_cbteVta_det> fa_cbteVta_det { get; set; }
        public virtual fa_cbteVta_tipo fa_cbteVta_tipo { get; set; }
        public virtual fa_cliente fa_cliente { get; set; }
        public virtual fa_cbteVta_Talonario fa_cbteVta_Talonario { get; set; }
    }
}
