//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_cliente_pto_emision_cliente
    {
        public int IdEmpresa { get; set; }
        public decimal IdCliente { get; set; }
        public int IdPuntoEmision { get; set; }
        public string cod_ptoemision { get; set; }
        public string ruc { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string mail1 { get; set; }
        public string mail2 { get; set; }
        public bool Estado { get; set; }
    }
}
