//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_orden_pedido_det
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdPuntoVta { get; set; }
        public decimal IdPedido { get; set; }
        public int Secuencial { get; set; }
        public decimal IdProducto { get; set; }
        public double dp_cantidad { get; set; }
        public double dp_precio { get; set; }
        public double dp_Porc_descuento { get; set; }
        public double cp_valor_desUni { get; set; }
        public double cp_PrecioFinal { get; set; }
        public double dp_subtotal { get; set; }
        public double dp_valor_impuesto_iva { get; set; }
        public string dp_detallexItems { get; set; }
        public double dp_por_impuesto_iva { get; set; }
        public string IdImpuesto_Iva { get; set; }
        public string IdImpuesto_Ice { get; set; }
        public double valor_impuesto_ice { get; set; }
        public double por_impuesto_ice { get; set; }
        public double dp_total { get; set; }
    }
}
