//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_cliente_contactos
    {
        public int IdEmpresa_cli { get; set; }
        public decimal IdCliente { get; set; }
        public int IdEmpresa_cont { get; set; }
        public decimal IdContacto { get; set; }
        public string observacion { get; set; }
    }
}
