//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_pedido_x_formaPago
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdPedido { get; set; }
        public string IdTipoFormaPago { get; set; }
        public int Secuencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Fecha_vct { get; set; }
        public int Dias_Plazo { get; set; }
        public double Por_Distribucion { get; set; }
        public double Valor { get; set; }
    }
}
