//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_cbteVta
    {
        public int IdEmpresa { get; set; }
        public string IdCbteVtaTipo { get; set; }
        public decimal IdCbteVta { get; set; }
        public string CodCbteVta { get; set; }
        public string num_CbteVta { get; set; }
        public int IdSucursal { get; set; }
        public int IdPuntoVta { get; set; }
        public Nullable<int> IdTipoNota { get; set; }
        public Nullable<int> IdCaja { get; set; }
        public decimal IdCliente { get; set; }
        public bool estado { get; set; }
        public string vt_Observacion { get; set; }
        public Nullable<System.DateTime> Fecha_Autorizacion { get; set; }
        public string num_autorizacion { get; set; }
        public int vt_plazo { get; set; }
        public Nullable<System.DateTime> vt_fecha_venc { get; set; }
        public Nullable<System.DateTime> vt_fecha { get; set; }
    }
}
