//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_catalogo_tipo
    {
        public int IdCatalogo_tipo { get; set; }
        public string nom_Catalogo_tipo { get; set; }
        public bool estado { get; set; }
    }
}
