//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_cotizacion_det
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdPuntoVta { get; set; }
        public decimal IdCotizacion { get; set; }
        public int Secuencial { get; set; }
        public decimal IdProducto { get; set; }
        public double dc_cantidad { get; set; }
        public double dc_precio { get; set; }
        public double dc_por_desUni { get; set; }
        public double dc_valor_desUni { get; set; }
        public double dc_precioFinal { get; set; }
        public double dc_subtotal { get; set; }
        public double dc_valor_impuesto_iva { get; set; }
        public string dc_detallexItems { get; set; }
        public double dc_por_impuesto_iva { get; set; }
        public string IdImpuesto_Iva { get; set; }
        public double dc_total { get; set; }
    }
}
