//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_devol_venta_det
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdPuntoVta { get; set; }
        public decimal IdDevolucion { get; set; }
        public int Secuencia { get; set; }
        public decimal IdProducto { get; set; }
        public double dv_cantidad { get; set; }
        public double dv_Precio { get; set; }
        public double dv_PorDescUni { get; set; }
        public double dv_ValordescUni { get; set; }
        public double dv_PrecioFinal { get; set; }
        public double dv_subtotal { get; set; }
        public double dv_valor_impuesto_iva { get; set; }
        public double dv_costo_Uni { get; set; }
        public string dv_detallexItems { get; set; }
        public double dv_por_impuesto_iva { get; set; }
        public string IdImpuesto_Iva { get; set; }
        public double dv_total { get; set; }
    }
}
