//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fac_cliente
    {
        public int IdEmpresa { get; set; }
        public decimal IdCliente { get; set; }
        public string cod_cliente { get; set; }
        public decimal IdPersona { get; set; }
        public int IdSucursal { get; set; }
        public int Idtipo_cliente { get; set; }
        public string IdTipoCredito { get; set; }
        public string cl_Cat_crediticia { get; set; }
        public int cl_plazo { get; set; }
        public double cl_porc_descuento { get; set; }
        public string IdCtaCble_cxc { get; set; }
        public string IdCtaCble_Anti { get; set; }
        public string IdCtaCble_cxc_Credito { get; set; }
        public string Observacion { get; set; }
        public string IdCiudad { get; set; }
        public double cl_Cupo { get; set; }
        public Nullable<decimal> IdClienteRelacionado { get; set; }
        public string cat_IdActividadComercial { get; set; }
        public bool Estado { get; set; }
        public string IdParroquia { get; set; }
        public string IdUsuario { get; set; }
        public System.DateTime Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
    }
}
