//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Facturacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_Facturacion : DbContext
    {
        public Entities_Facturacion()
            : base("name=Entities_Facturacion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<fa_cbteVta> fa_cbteVta { get; set; }
        public DbSet<fa_cbteVta_det> fa_cbteVta_det { get; set; }
        public DbSet<fa_cbteVta_tipo> fa_cbteVta_tipo { get; set; }
        public DbSet<fa_cliente> fa_cliente { get; set; }
        public DbSet<fa_cbteVta_Talonario> fa_cbteVta_Talonario { get; set; }
    }
}
