CREATE TABLE [dbo].[con_cbtecble] (
    [IdEmpresa]        INT           NOT NULL,
    [IdTipoCbte]       INT           NOT NULL,
    [IdCbteCble]       NUMERIC (18)  NOT NULL,
    [CodCbteCble]      VARCHAR (20)  NOT NULL,
    [IdPeriodo]        INT           NOT NULL,
    [cb_Fecha]         DATETIME      NOT NULL,
    [cb_Valor]         FLOAT (53)    NOT NULL,
    [IdSucursal]       INT           NOT NULL,
    [cb_Observacion]   VARCHAR (MAX) NOT NULL,
    [cb_Secuencia]     NUMERIC (10)  NOT NULL,
    [estado]           BIT           NOT NULL,
    [Para_conciliar]   BIT           NOT NULL,
    [IdUsuario]        VARCHAR (20)  NOT NULL,
    [IdUsuarioAnu]     VARCHAR (20)  NULL,
    [cb_MotivoAnu]     VARCHAR (100) NULL,
    [IdUsuarioUltModi] VARCHAR (20)  NULL,
    [cb_FechaAnu]      DATETIME      NULL,
    [cb_FechaTransac]  DATETIME      NOT NULL,
    [cb_FechaUltModi]  DATETIME      NULL,
    CONSTRAINT [PK_con_cbtecble] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdTipoCbte] ASC, [IdCbteCble] ASC),
    CONSTRAINT [FK_con_cbtecble_con_cbtecble_tipo] FOREIGN KEY ([IdEmpresa], [IdTipoCbte]) REFERENCES [dbo].[con_cbtecble_tipo] ([IdEmpresa], [IdTipoCbte]),
    CONSTRAINT [FK_con_cbtecble_con_periodo] FOREIGN KEY ([IdEmpresa], [IdPeriodo]) REFERENCES [dbo].[con_periodo] ([IdEmpresa], [IdPeriodo]),
    CONSTRAINT [FK_con_cbtecble_tb_sucursal] FOREIGN KEY ([IdEmpresa], [IdSucursal]) REFERENCES [dbo].[tb_sucursal] ([IdEmpresa], [IdSucursal])
);

