CREATE TABLE [dbo].[fac_parametro] (
    [IdEmpresa]                                INT             NOT NULL,
    [IdMovi_inven_tipo_Factura]                INT             NULL,
    [pa_porc_max_total_item_x_despa_Guia]      FLOAT (53)      NULL,
    [IdMovi_inven_tipo_Dev_Vta]                INT             NULL,
    [IdMovi_inven_tipo_Factura_Anulacion]      INT             NULL,
    [IdMovi_inven_tipo_Dev_Vta_Anulacion]      INT             NULL,
    [Tipo_NC_x_DevVta]                         INT             NULL,
    [IdDepartamento_x_DevVta]                  INT             NULL,
    [IdTipoCbteCble_Factura]                   INT             NULL,
    [IdTipoCbteCble_Factura_Reverso]           INT             NULL,
    [IdTipoCbteCble_Factura_Costo_VTA]         INT             NULL,
    [IdTipoCbteCble_Factura_Costo_VTA_Reverso] INT             NULL,
    [IdTipoCbteCble_NC]                        INT             NULL,
    [IdTipoCbteCble_NC_Reverso]                INT             NULL,
    [IdTipoCbteCble_ND]                        INT             NULL,
    [IdTipoCbteCble_ND_Reverso]                INT             NULL,
    [SeImprimiGuiaRemiAuto]                    CHAR (1)        NULL,
    [NumeroDeItemFact]                         INT             NULL,
    [TipoCobroDafaultFactu]                    VARCHAR (20)    NULL,
    [IdCaja_Default_Factura]                   INT             NULL,
    [IdCtaCble_x_anticipo_cliente]             VARCHAR (20)    NULL,
    [pa_IdTipoNota_NC_x_Anulacion]             INT             NULL,
    [IdEstadoAprobacion]                       CHAR (1)        NULL,
    [pa_ruta_descarga_xml_fac_elct]            VARCHAR (500)   NULL,
    [File_Reporte_FacturaDiseño]               VARBINARY (MAX) NULL,
    [File_Reporte_Nota_CRED_DEB]               VARBINARY (MAX) NULL,
    [IdCtaCble_IVA]                            VARCHAR (20)    NULL,
    [IdCtaCble_SubTotal_Vtas_x_Default]        VARCHAR (20)    NULL,
    [IdCtaCble_CXC_Vtas_x_Default]             VARCHAR (20)    NULL,
    [pa_X_Defecto_la_factura_es_cbte_elect]    BIT             NULL,
    [pa_X_Defecto_la_guia_es_cbte_elect]       BIT             NULL,
    [pa_X_Defecto_la_ND_es_cbte_elect]         BIT             NULL,
    [pa_X_Defecto_la_NC_es_cbte_elect]         BIT             NULL,
    CONSTRAINT [PK_fa_parametro] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC)
);

