CREATE TABLE [dbo].[fac_guia_remision] (
    [IdEmpresa]           INT            NOT NULL,
    [IdSucursal]          INT            NOT NULL,
    [IdPuntoVta]          INT            NOT NULL,
    [IdGuiaRemision]      NUMERIC (18)   NOT NULL,
    [CodGuiaRemision]     VARCHAR (20)   NOT NULL,
    [num_CbteVta]         VARCHAR (150)  NULL,
    [num_autorizacion]    VARCHAR (150)  NULL,
    [Fecha_Autorizacion]  DATETIME       NULL,
    [IdCliente]           NUMERIC (18)   NOT NULL,
    [IdVendedor]          INT            NOT NULL,
    [IdTransportista]     NUMERIC (18)   NOT NULL,
    [gi_fecha]            DATETIME       NOT NULL,
    [gi_plazo]            NUMERIC (10)   NULL,
    [gi_fech_venc]        DATETIME       NULL,
    [gi_Observacion]      VARCHAR (1000) NULL,
    [gi_TotalKilos]       FLOAT (53)     NULL,
    [gi_TotalQuintales]   FLOAT (53)     NULL,
    [estado]              BIT            NOT NULL,
    [IdUsuario]           VARCHAR (20)   NOT NULL,
    [Fecha_Transac]       DATETIME       NOT NULL,
    [IdUsuarioUltMod]     VARCHAR (20)   NULL,
    [Fecha_UltMod]        DATETIME       NULL,
    [IdUsuarioUltAnu]     VARCHAR (20)   NULL,
    [Fecha_UltAnu]        DATETIME       NULL,
    [nom_pc]              VARCHAR (50)   NOT NULL,
    [ip]                  VARCHAR (25)   NOT NULL,
    [MotiAnula]           VARCHAR (200)  NULL,
    [Impreso]             BIT            NULL,
    [IdPeriodo]           INT            NOT NULL,
    [gi_FechaIniTraslado] DATETIME       NOT NULL,
    [gi_FechaFinTraslado] DATETIME       NOT NULL,
    [placa]               VARCHAR (20)   NOT NULL,
    [ruta]                VARCHAR (300)  NOT NULL,
    [Direccion_Origen]    VARCHAR (300)  NOT NULL,
    [Direccion_Destino]   VARCHAR (300)  NOT NULL,
    CONSTRAINT [PK_fa_guia_remision] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdSucursal] ASC, [IdPuntoVta] ASC, [IdGuiaRemision] ASC)
);

