CREATE TABLE [dbo].[fac_cbteVta_det] (
    [IdEmpresa]           INT           NOT NULL,
    [IdCbteVtaTipo]       VARCHAR (20)  NOT NULL,
    [IdCbteVta]           NUMERIC (18)  NOT NULL,
    [secuencia]           INT           NOT NULL,
    [IdProducto]          NUMERIC (18)  NOT NULL,
    [observacion_det]     VARCHAR (MAX) NOT NULL,
    [cantidad]            FLOAT (53)    NOT NULL,
    [precio]              FLOAT (53)    NOT NULL,
    [por_descuento]       FLOAT (53)    NOT NULL,
    [valor_descuento]     FLOAT (53)    NOT NULL,
    [precio_final]        FLOAT (53)    NOT NULL,
    [subtotal]            FLOAT (53)    NOT NULL,
    [valor_impuesto_iva]  FLOAT (53)    NOT NULL,
    [por_impuesto_iva]    FLOAT (53)    NOT NULL,
    [IdImpuesto_Iva]      VARCHAR (20)  NOT NULL,
    [total]               FLOAT (53)    NOT NULL,
    [IdPunto_Cargo]       INT           NULL,
    [IdPunto_cargo_grupo] INT           NULL,
    [IdImpuesto_Ice]      VARCHAR (20)  NULL,
    [valor_impuesto_ice]  FLOAT (53)    NULL,
    [por_impuesto_ice]    FLOAT (53)    NULL,
    CONSTRAINT [PK_fac_cbteVta_det] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdCbteVtaTipo] ASC, [IdCbteVta] ASC, [secuencia] ASC)
);

