CREATE TABLE [dbo].[tb_contacto] (
    [IdEmpresa]           INT            NOT NULL,
    [IdContacto]          NUMERIC (18)   NOT NULL,
    [IdPersona]           NUMERIC (18)   NOT NULL,
    [CodContacto]         VARCHAR (51)   NOT NULL,
    [Organizacion]        VARCHAR (150)  NOT NULL,
    [Cargo]               VARCHAR (150)  NOT NULL,
    [Mostrar_como]        VARCHAR (250)  NOT NULL,
    [Fecha_alta]          DATETIME       NOT NULL,
    [Fecha_Ult_Contacto]  DATETIME       NOT NULL,
    [IdCiudad]            VARCHAR (25)   NOT NULL,
    [IdNacionalidad]      VARCHAR (10)   NOT NULL,
    [Notas]               TEXT           NOT NULL,
    [Pagina_Web]          VARCHAR (150)  NOT NULL,
    [Codigo_postal]       VARCHAR (50)   NOT NULL,
    [foto]                IMAGE          NULL,
    [UsuarioCreacion]     NVARCHAR (50)  NULL,
    [UsuarioModificacion] NVARCHAR (50)  NULL,
    [UsuarioAnulacion]    NVARCHAR (50)  NULL,
    [FechaCreacion]       DATETIME       NULL,
    [FechaModificacion]   DATETIME       NULL,
    [FechaAnulacion]      DATETIME       NULL,
    [MotivoAnulacion]     NVARCHAR (150) NULL,
    [Estado]              CHAR (1)       NOT NULL,
    [IdPais]              VARCHAR (10)   NULL,
    [IdProvincia]         VARCHAR (25)   NULL,
    CONSTRAINT [PK_tb_contacto] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdContacto] ASC)
);

