//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.SeguridadAcceso
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_Seguridad_Accesos : DbContext
    {
        public Entities_Seguridad_Accesos()
            : base("name=Entities_Seguridad_Accesos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<seg_menu_x_seg_usuario> seg_menu_x_seg_usuario { get; set; }
        public DbSet<seg_perfil> seg_perfil { get; set; }
        public DbSet<seg_perfil_x_seg_menu> seg_perfil_x_seg_menu { get; set; }
        public DbSet<seg_usuario> seg_usuario { get; set; }
        public DbSet<seg_usuario_sesion> seg_usuario_sesion { get; set; }
        public DbSet<seg_menu> seg_menu { get; set; }
    }
}
