//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.SeguridadAcceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_usuario_sesion
    {
        public decimal IdRegistro { get; set; }
        public string IdUsuario { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string tipo { get; set; }
        public string ip { get; set; }
        public string equipo { get; set; }
    
        public virtual seg_usuario seg_usuario { get; set; }
    }
}
