//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.SeguridadAcceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_usuario
    {
        public seg_usuario()
        {
            this.seg_menu_x_seg_usuario = new HashSet<seg_menu_x_seg_usuario>();
            this.seg_usuario_sesion = new HashSet<seg_usuario_sesion>();
        }
    
        public string IdUsuario { get; set; }
        public string nom_usuario { get; set; }
        public string contrasenia { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> IdPerfil { get; set; }
        public bool Exigir_directivas_seguridad { get; set; }
        public bool Exigir_expiracion_contrasenia { get; set; }
        public bool usuario_debe_cambiar_contra_inicio_sesion { get; set; }
        public System.DateTime Fecha_expiracion_contrasenia { get; set; }
    
        public virtual ICollection<seg_menu_x_seg_usuario> seg_menu_x_seg_usuario { get; set; }
        public virtual ICollection<seg_usuario_sesion> seg_usuario_sesion { get; set; }
    }
}
