//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.SeguridadAcceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_menu
    {
        public seg_menu()
        {
            this.seg_menu_x_seg_usuario = new HashSet<seg_menu_x_seg_usuario>();
            this.seg_perfil_x_seg_menu = new HashSet<seg_perfil_x_seg_menu>();
        }
    
        public string IdMenu { get; set; }
        public string cod_menu { get; set; }
        public string nom_menu { get; set; }
        public string IdMenuPadre { get; set; }
        public bool estado { get; set; }
        public string path_web { get; set; }
        public string nom_webform { get; set; }
        public string observacion { get; set; }
        public string IdFormulario { get; set; }
        public string IdReporte { get; set; }
        public Nullable<bool> esFormulario { get; set; }
        public Nullable<bool> esReporte { get; set; }
    
        public virtual ICollection<seg_menu_x_seg_usuario> seg_menu_x_seg_usuario { get; set; }
        public virtual ICollection<seg_perfil_x_seg_menu> seg_perfil_x_seg_menu { get; set; }
    }
}
