//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.SeguridadAcceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_perfil
    {
        public seg_perfil()
        {
            this.seg_perfil_x_seg_menu = new HashSet<seg_perfil_x_seg_menu>();
        }
    
        public int IdPerfil { get; set; }
        public string nom_perfil { get; set; }
        public bool estado { get; set; }
    
        public virtual ICollection<seg_perfil_x_seg_menu> seg_perfil_x_seg_menu { get; set; }
    }
}
