//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.SeguridadAcceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_perfil_x_seg_menu
    {
        public int IdPerfil { get; set; }
        public string IdMenu { get; set; }
        public string observacion { get; set; }
    
        public virtual seg_menu seg_menu { get; set; }
        public virtual seg_perfil seg_perfil { get; set; }
    }
}
