//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.SeguridadAcceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_perfil_x_seg_menu
    {
        public int IdPerfil { get; set; }
        public string IdMenu { get; set; }
        public string observacion { get; set; }
    
        public virtual seg_perfil seg_perfil { get; set; }
        public virtual seg_menu seg_menu { get; set; }
    }
}
