//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Sistemas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_Sistemas : DbContext
    {
        public Entities_Sistemas()
            : base("name=Entities_Sistemas")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_sis_Formulario> tb_sis_Formulario { get; set; }
        public DbSet<tb_catalogo> tb_catalogo { get; set; }
        public DbSet<tb_catalogo_tipo> tb_catalogo_tipo { get; set; }
        public DbSet<tb_sis_reporte> tb_sis_reporte { get; set; }
    }
}
