//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.Sistemas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_catalogo
    {
        public string IdCatalogo { get; set; }
        public string nom_catalogo { get; set; }
        public bool estado { get; set; }
        public string IdCatalogo_tipo { get; set; }
    }
}
