//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.General
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_General : DbContext
    {
        public Entities_General()
            : base("name=Entities_General")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_catalogo> tb_catalogo { get; set; }
        public DbSet<tb_catalogo_tipo> tb_catalogo_tipo { get; set; }
        public DbSet<tb_empresa> tb_empresa { get; set; }
        public DbSet<tb_impuesto> tb_impuesto { get; set; }
        public DbSet<tb_Impuesto_tipo> tb_Impuesto_tipo { get; set; }
        public DbSet<tb_persona> tb_persona { get; set; }
        public DbSet<tb_puntoVta> tb_puntoVta { get; set; }
        public DbSet<tb_sucursal> tb_sucursal { get; set; }
    }
}
