//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.General
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_banco
    {
        public int IdBanco { get; set; }
        public string nom_banco { get; set; }
        public bool Estado { get; set; }
        public string CodigoLegal { get; set; }
        public bool TieneFormatoTransferencia { get; set; }
    }
}
