//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.General
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Impuesto_tipo
    {
        public tb_Impuesto_tipo()
        {
            this.tb_impuesto = new HashSet<tb_impuesto>();
        }
    
        public string IdImpuesto_tipo { get; set; }
        public string nom_Impuesto_tipo { get; set; }
    
        public virtual ICollection<tb_impuesto> tb_impuesto { get; set; }
    }
}
