//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.General
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_modulo
    {
        public string IdModulo { get; set; }
        public string nom_modulo { get; set; }
        public string Nom_Carpeta { get; set; }
        public Nullable<bool> Se_Cierra { get; set; }
    }
}
