//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.General
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_persona
    {
        public decimal IdPersona { get; set; }
        public string cod_persona { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string razon_social { get; set; }
        public string IdTipoDocumento { get; set; }
        public string Num_documento { get; set; }
        public string IdTipoPersona { get; set; }
        public bool estado { get; set; }
    }
}
