//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.General
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_Mensajes_sys
    {
        public decimal IdSecuencia { get; set; }
        public string IdMensaje { get; set; }
        public string Mensaje_Esp { get; set; }
        public string Mensaje_Englesh { get; set; }
        public bool Estado { get; set; }
    }
}
