//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ErpSys.Data.General
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_reporte
    {
        public string IdReporte { get; set; }
        public string Nom_reporte { get; set; }
        public string Nom_Corto_reporte { get; set; }
        public string IdModulo { get; set; }
        public string VistaRpt { get; set; }
        public string Formulario { get; set; }
        public string Class_NomReporte { get; set; }
        public string nom_Asembly { get; set; }
        public int Orden { get; set; }
        public string Observacion { get; set; }
        public byte[] imagen { get; set; }
        public int VersionActual { get; set; }
        public string Tipo_Balance { get; set; }
        public string SQuery { get; set; }
        public string Class_Info { get; set; }
        public string Class_Bus { get; set; }
        public string Class_Data { get; set; }
        public int IdGrupo_Reporte { get; set; }
        public bool se_Muestra_Admin_Reporte { get; set; }
        public bool Estado { get; set; }
        public string Store_proce_rpt { get; set; }
        public byte[] Disenio_reporte { get; set; }
    }
}
